[package]
name = "steam-status-scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.30"
clokwerk = "0.4.0"
console = "0.15.7"
open = "5.0.0"
tray-item = "0.8.0"
